### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by altynismailova** [ldesousa/ldesousa.github.io#1]

**Comment by altynismailova** [comment]
Hello, @ldesousa!
My name is Altyn. I am in my fourth year of studies towards a Bachelor's in Computer Sciences. I have a question to you regarding a project you intended to contribute to. Can I ask my question via email? But I don't know your email address

**Comment by ldesousa** [comment]
You can find my e-mail address in the footer of this site (note that it is in construction):
ldesousa.github.io
